name = "agent-wasm"
version = "0.1.0"
defaultTargets = [
  "AgentWasm", "BindingTest", "PhaseTest", "BindingLawsTest",
  "ErasedContextTest", "IndexedTypeTest", "DependentContextTest",
  "DependentTermTest", "DependentBranchTest"
]

[[lean_lib]]
name = "AgentWasm"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "BindingTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "PhaseTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "BindingLawsTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "ErasedContextTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "IndexedTypeTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "DependentContextTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "DependentTermTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_lib]]
name = "DependentBranchTest"
srcDir = "proof-test"
moreLeanArgs = ["-DwarningAsError=true"]
